apiVersion: v1
kind: ReplicationController
metadata:
  name: cat-v1
spec:
  replicas: 3
  template:
    metadata:
      name: cat
      labels:
        app: cat
    spec:
      containers:
      - image: spotmax/cat:v1
        name: cat
---
apiVersion: v1
kind: Service
metadata:
  name: cat
spec:
  type: LoadBalancer
  selector:
    app: cat
  ports:
  - port: 80
    targetPort: 5000
