apiVersion: v1
kind: ReplicationController
metadata:
  name: cat-v1
spec:
  replicas: 3
  template:
    metadata:
      name: cat
      labels:
        app: cat
    spec:
      containers:
        - image: spotmax/cat:v1
          name: cat
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cat
spec:
  type: NodePort
  selector:
    app: cat
  ports:
    - port: 80
      targetPort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cat
spec:
  rules:
    - host: cat.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: cat
              servicePort: 80
