apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: kibana
  namespace: default
spec:
  rules:
    - host: kibana.spotmaxtech.com
      http:
        paths:
          - backend:
              serviceName: kibana-kibana
              servicePort: 5601
            path: /
