apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: disk
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  type: cloud_efficiency
  zoneid: ap-southeast-1b,ap-southeast-1a
provisioner: alicloud/disk
volumeBindingMode: WaitForFirstConsumer
