apiVersion: batch/v1
kind: Job
metadata:
  name: multi-parallel-batch-job
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: spotmax/batch-job
