apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: cat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cat
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
        - name: cat
          image: spotmax/cat
          ports:
            - containerPort: 5000
              protocol: TCP
